apiVersion: v1
kind: Service
metadata:
  name: immunogen-api
  labels:
    app: immunogen-api
spec:
  type: NodePort
  selector:
    app: immunogen-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
